// PocketBase settings synced from environment variables on every boot.
//
// Why this exists: PocketBase stores its "app URL" (Settings -> Application) in
// the database. On Railway the container hostname (127.0.0.1 / an internal DNS
// name) is NOT the URL visitors use, so links generated by PocketBase — email
// verification/reset links, OAuth2 redirects, file URLs, and the admin
// dashboard's "App URL" field — pointed at localhost instead of the live
// deployment. This hook re-derives the public URL from the environment on each
// start so it always matches the Railway deployment, even after domain changes
// or restores from backup.
//
// Env vars consumed (all optional):
//   PB_PUBLIC_URL           - full public URL, e.g. https://example.com
//                             (use when you have a custom domain; takes
//                             precedence over the Railway-generated one)
//   RAILWAY_PUBLIC_DOMAIN   - Railway-injected; e.g. myapp.up.railway.app
//   PB_APP_NAME             - overrides the dashboard/UI app name
//   PB_SMTP_HOST/PORT/USERNAME/PASSWORD/TLS/AUTH_METHOD/LOCAL_NAME
//   PB_BACKUPS_CRON         - optional cron for scheduled backups, e.g. 0 2 * * *
//   PB_BACKUPS_CRON_MAX_KEEP - how many scheduled backups to retain (default 7)
//
// Changes made here apply to the running settings AND are persisted to the DB,
// so they survive restarts. Admin-UI changes to these specific fields are
// re-applied on the next deploy — keep your source of truth in Railway env vars.

onBootstrap((e) => {
  e.next();

  const settings = $app.settings();
  let changed = false;

  // --- Public URL ----------------------------------------------------------
  // PB_PUBLIC_URL wins (custom domains); otherwise build one from Railway's
  // auto-injected domain, e.g. https://myapp.up.railway.app
  const publicUrl = $os.getenv("PB_PUBLIC_URL") || (() => {
    const domain = $os.getenv("RAILWAY_PUBLIC_DOMAIN");
    return domain ? "https://" + domain : "";
  })();

  if (publicUrl && settings.meta.appURL !== publicUrl) {
    console.log("==> Setting PocketBase app URL to " + publicUrl);
    settings.meta.appURL = publicUrl;
    changed = true;
  }

  // --- App name ------------------------------------------------------------
  const appName = $os.getenv("PB_APP_NAME");
  if (appName && settings.meta.appName !== appName) {
    settings.meta.appName = appName;
    changed = true;
  }

  // --- SMTP ----------------------------------------------------------------
  // Enables transactional email (password resets, verification, OTP, etc.)
  // when PB_SMTP_HOST is set. Port/auth method default sensibly; password is
  // only written when explicitly provided so it can never be blanked by env.
  const smtpHost = $os.getenv("PB_SMTP_HOST");
  if (smtpHost) {
    const smtp = settings.smtp;
    smtp.enabled = true;
    smtp.host = smtpHost;
    smtp.port = parseInt($os.getenv("PB_SMTP_PORT") || "587", 10);
    const smtpUser = $os.getenv("PB_SMTP_USERNAME") || "";
    smtp.username = smtpUser;
    smtp.authMethod = $os.getenv("PB_SMTP_AUTH_METHOD") || (smtpUser ? "PLAIN" : "LOGIN");
    const smtpPass = $os.getenv("PB_SMTP_PASSWORD");
    if (smtpPass) {
      smtp.password = smtpPass;
    }
    smtp.tls = ($os.getenv("PB_SMTP_TLS") || "true").toLowerCase() === "true";
    const smtpLocalName = $os.getenv("PB_SMTP_LOCAL_NAME");
    if (smtpLocalName) {
      smtp.localName = smtpLocalName;
    }
    changed = true;
  }

  // --- Scheduled backups ---------------------------------------------------
  // Only touches the cron fields; leaves S3 storage/backup config alone.
  const backupsCron = $os.getenv("PB_BACKUPS_CRON");
  if (backupsCron) {
    settings.backups.cron = backupsCron;
    settings.backups.cronMaxKeep = parseInt($os.getenv("PB_BACKUPS_CRON_MAX_KEEP") || "7", 10);
    changed = true;
  }

  if (changed) {
    $app.save(settings);
  }
});
